---
image: python:latest

variables:
  PIP_CACHE: ${CI_PROJECT_DIR}/pip_cache
cache:
  paths:
    - ${CI_PROJECT_DIR}/pip_cache
  key: ${CI_PROJECT_ID}

services:
  - docker:dind

stages:
  - test

before_script:
  - apt-get update && apt-get install make
  - python3 --version

pylint:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install --upgrade pip pylint pylint-exit anybadge
    - mkdir ./pylint
    - make pylint
    - cd ./module && pylint *  -f parseable --output-format=text . | tee ../pylint/pylint.log || pylint-exit $? && cd -
    - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
    - anybadge --label=Pylint --file=pylint/pylint.svg --value=$PYLINT_SCORE 2=red 4=orange 8=yellow 10=green
    - echo "Pylint score is $PYLINT_SCORE"
  artifacts:
    paths:
      - ./pylint/

coverage:
  stage: test
  extends: .pipelinesetup
  script:
    - pip3 install codecov virtualenv
    # install an outdated package for the negative test test_list_outdated
    - pip3 install yarl==1.1.0
    - coverage run ./module/main/tests/unit.py

.pipelinesetup:
  before_script:
    - mkdir -p $PIP_CACHE
    - apt-get update && apt-get install make