---
image: python:slim

variables:
  GIT_DEPTH: "1"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

services:
  - docker:dind

stages:
  - build
  - lint
  - test
  - deploy

before_script:
  # - apk update && apk add --no-cache docker
  #   python3-dev py3-pip docker gcc git curl build-base
  #   autoconf make automake py3-cryptography linux-headers
  #   musl-dev libffi-dev openssl-dev openssh
  # - docker info
  - apt-get update && apt-get install make
  - python3 --version

build:
  stage: lint
  script:
    - pip3 install --upgrade pip pylint
    - make pylint
